"""BT2: workspace_scoped_live scoring (forbidden work ids + abstain_keywords)."""

from __future__ import annotations

import json
from pathlib import Path

from eval.retrieval.metrics import score_workspace_scoped_live_answer
from science_graphrag.retrieval import GroundedAnswer

_REPO_ROOT = Path(__file__).resolve().parents[2]
_LIVE_ARTIFACT = _REPO_ROOT / "eval" / "results" / "current-retrieval-workspace-scoped-live.json"


def test_forbidden_corpus_work_id_in_citations_fails() -> None:
    """Citing a forbidden corpus work id increments violation count and fails the case."""
    gold = {
        "schema_version": 1,
        "workspace_id": "ws",
        "forbidden_corpus_work_ids": ["leaked_work"],
        "forbidden_violation_gate": 0,
        "expected_citations": [],
        "min_hit_count": 0,
    }
    ga = GroundedAnswer(
        answer="answer",
        citations=[{"work_id": "leaked_work", "chunk_fingerprint": "fp1"}],
        graph_context={},
        retrieval_trace={"hit_count": 1, "workspace_id": "ws"},
    )
    m = score_workspace_scoped_live_answer(ga, gold, workspace_catalog=None)
    assert m["forbidden_work_id_violation_count"] >= 1
    assert m["passed"] is False


def test_run_metadata_embedding_model_not_mock() -> None:
    """The committed workspace_scoped_live artifact must not use mock embedding (BT2 honesty guard)."""
    if not _LIVE_ARTIFACT.is_file():
        return  # artifact not yet generated — skip guard
    data = json.loads(_LIVE_ARTIFACT.read_text(encoding="utf-8"))
    meta = data.get("run_metadata") or {}
    cases = data.get("cases") or []
    # run_metadata.embedding_model must not be "mock" when present
    if "embedding_model" in meta:
        assert (
            meta["embedding_model"] != "mock"
        ), "embedding_model in run_metadata is 'mock' — artifact was not generated by a real run"
    # Verify at least one case has a non-mock embedding in its retrieval_trace
    non_mock_found = False
    for c in cases:
        rt = c.get("retrieval_trace") or {}
        emb = rt.get("embedding") or {}
        emb_model = str(emb.get("embedding_model") or rt.get("embedding_model") or "").lower()
        if emb_model and emb_model != "mock":
            non_mock_found = True
            break
    assert non_mock_found, (
        "No case in workspace_scoped_live artifact has a real (non-mock) embedding_model "
        "in retrieval_trace — run was not performed against a real stack"
    )


def test_abstain_keywords_must_contain_any_requires_phrase_or_empty() -> None:
    """``abstain_keywords`` + ``must_contain_any`` requires a keyword hit (or empty abstain)."""
    gold = {
        "schema_version": 1,
        "workspace_id": "ws",
        "forbidden_corpus_work_ids": [],
        "forbidden_violation_gate": 0,
        "expected_citations": [],
        "min_hit_count": 0,
        "answer_metric": {
            "type": "abstain_keywords",
            "must_contain_any": ["not enough information"],
        },
    }
    ga_bad = GroundedAnswer(
        answer="I will guess wildly.",
        citations=[],
        graph_context={},
        retrieval_trace={"hit_count": 0, "workspace_id": "ws"},
    )
    m_bad = score_workspace_scoped_live_answer(ga_bad, gold, workspace_catalog=None)
    assert m_bad["answer_metric_type"] == "abstain_keywords"
    assert m_bad["passed"] is False

    ga_ok = GroundedAnswer(
        answer="Not enough information in the corpus.",
        citations=[],
        graph_context={},
        retrieval_trace={"hit_count": 0, "workspace_id": "ws"},
    )
    m_ok = score_workspace_scoped_live_answer(ga_ok, gold, workspace_catalog=None)
    assert m_ok["abstain_keyword_hit"] is True
    assert m_ok["passed"] is True
