/**
 * Graph reasoning, claims, and agent experiments (CLI / catalog surfaces).
 * @type {object[]}
 */
export const EXPERIMENTS_PART_B = [
  {
    id: "multihop_v2",
    titleKey: "benchmarkCatalog.experiment.multihopV2.title",
    descriptionKey: "benchmarkCatalog.experiment.multihopV2.description",
    benchmarkType: "graph_reasoning",
    primaryMetricKeys: ["benchmarkCatalog.metric.recall", "benchmarkCatalog.metric.precision"],
    secondaryMetricKeys: ["benchmarkCatalog.metric.diagnostics"],
    defaultScopeKey: "benchmarkCatalog.scope.multihopPack",
    recommendedCompareMode: "cli_artifact",
    runnableSurface: "cli_only",
    uiFamily: null,
    launcherScopePreset: null,
    reportCritical: true,
    packIds: ["report_critical", "reasoning"],
  },
  {
    id: "claims_production",
    titleKey: "benchmarkCatalog.experiment.claimsProduction.title",
    descriptionKey: "benchmarkCatalog.experiment.claimsProduction.description",
    benchmarkType: "claims",
    primaryMetricKeys: ["benchmarkCatalog.metric.precision", "benchmarkCatalog.metric.recall", "benchmarkCatalog.metric.f1"],
    secondaryMetricKeys: ["benchmarkCatalog.metric.diagnostics"],
    defaultScopeKey: "benchmarkCatalog.scope.claimsProduction",
    recommendedCompareMode: "cli_artifact",
    runnableSurface: "cli_only",
    uiFamily: null,
    launcherScopePreset: null,
    reportCritical: false,
    packIds: ["claims"],
  },
  {
    id: "claims_paraphrase",
    titleKey: "benchmarkCatalog.experiment.claimsParaphrase.title",
    descriptionKey: "benchmarkCatalog.experiment.claimsParaphrase.description",
    benchmarkType: "claims",
    primaryMetricKeys: ["benchmarkCatalog.metric.precision", "benchmarkCatalog.metric.recall", "benchmarkCatalog.metric.f1"],
    secondaryMetricKeys: ["benchmarkCatalog.metric.diagnostics"],
    defaultScopeKey: "benchmarkCatalog.scope.claimsParaphrase",
    recommendedCompareMode: "cli_artifact",
    runnableSurface: "cli_only",
    uiFamily: null,
    launcherScopePreset: null,
    reportCritical: true,
    packIds: ["report_critical", "claims"],
  },
  {
    id: "agent_tools_live",
    titleKey: "benchmarkCatalog.experiment.agentToolsLive.title",
    descriptionKey: "benchmarkCatalog.experiment.agentToolsLive.description",
    benchmarkType: "agent",
    primaryMetricKeys: ["benchmarkCatalog.metric.judgeScore", "benchmarkCatalog.metric.latency"],
    secondaryMetricKeys: ["benchmarkCatalog.metric.diagnostics"],
    defaultScopeKey: "benchmarkCatalog.scope.agentLive",
    recommendedCompareMode: "cli_artifact",
    runnableSurface: "cli_only",
    uiFamily: null,
    launcherScopePreset: null,
    reportCritical: true,
    packIds: ["report_critical", "reasoning"],
  },
];
