/**
 * UI + catalog extraction experiments (Run Lab families layer1/layer2/graph + early retrieval).
 * @type {object[]}
 */
export const EXPERIMENTS_PART_A = [
  {
    id: "layer1_nightly",
    titleKey: "benchmarkCatalog.experiment.layer1Nightly.title",
    descriptionKey: "benchmarkCatalog.experiment.layer1Nightly.description",
    benchmarkType: "extraction",
    primaryMetricKeys: ["benchmarkCatalog.metric.macroPRF1", "benchmarkCatalog.metric.rougeL"],
    secondaryMetricKeys: ["benchmarkCatalog.metric.failedCount"],
    defaultScopeKey: "benchmarkCatalog.scope.nightlyTier",
    recommendedCompareMode: "two_runs_same_family",
    runnableSurface: "ui",
    uiFamily: "layer1",
    launcherScopePreset: "nightly",
    reportCritical: true,
    packIds: ["report_critical", "extraction"],
  },
  {
    id: "layer2_semantic",
    titleKey: "benchmarkCatalog.experiment.layer2Semantic.title",
    descriptionKey: "benchmarkCatalog.experiment.layer2Semantic.description",
    benchmarkType: "extraction",
    primaryMetricKeys: ["benchmarkCatalog.metric.macroPRF1", "benchmarkCatalog.metric.rougeL"],
    secondaryMetricKeys: ["benchmarkCatalog.metric.failedCount"],
    defaultScopeKey: "benchmarkCatalog.scope.semanticGold",
    recommendedCompareMode: "two_runs_same_family",
    runnableSurface: "ui",
    uiFamily: "layer2",
    launcherScopePreset: "nightly",
    reportCritical: true,
    packIds: ["report_critical", "extraction"],
  },
  {
    id: "graph_cites",
    titleKey: "benchmarkCatalog.experiment.graphCites.title",
    descriptionKey: "benchmarkCatalog.experiment.graphCites.description",
    benchmarkType: "extraction",
    primaryMetricKeys: ["benchmarkCatalog.metric.graphExpectations"],
    secondaryMetricKeys: ["benchmarkCatalog.metric.cliOrCatalog"],
    defaultScopeKey: "benchmarkCatalog.scope.graphCatalog",
    recommendedCompareMode: "two_runs_same_family",
    runnableSurface: "catalog",
    uiFamily: "graph",
    launcherScopePreset: null,
    reportCritical: false,
    packIds: ["extraction"],
  },
  {
    id: "workspace_scoped_live",
    titleKey: "benchmarkCatalog.experiment.workspaceScopedLive.title",
    descriptionKey: "benchmarkCatalog.experiment.workspaceScopedLive.description",
    benchmarkType: "retrieval",
    primaryMetricKeys: [
      "benchmarkCatalog.metric.hitCount",
      "benchmarkCatalog.metric.hitAtK",
      "benchmarkCatalog.metric.mrr",
    ],
    secondaryMetricKeys: ["benchmarkCatalog.metric.forbiddenViolations"],
    defaultScopeKey: "benchmarkCatalog.scope.liveWorkspace",
    recommendedCompareMode: "cli_artifact",
    runnableSurface: "cli_only",
    uiFamily: null,
    launcherScopePreset: null,
    reportCritical: true,
    packIds: ["report_critical", "reasoning"],
  },
  {
    id: "hybrid_ablation_live",
    titleKey: "benchmarkCatalog.experiment.hybridAblationLive.title",
    descriptionKey: "benchmarkCatalog.experiment.hybridAblationLive.description",
    benchmarkType: "retrieval",
    primaryMetricKeys: [
      "benchmarkCatalog.metric.hitCount",
      "benchmarkCatalog.metric.hitAtK",
      "benchmarkCatalog.metric.mrr",
    ],
    secondaryMetricKeys: ["benchmarkCatalog.metric.forbiddenViolations"],
    defaultScopeKey: "benchmarkCatalog.scope.hybridAblation",
    recommendedCompareMode: "cli_artifact",
    runnableSurface: "cli_only",
    uiFamily: null,
    launcherScopePreset: null,
    reportCritical: true,
    packIds: ["report_critical", "reasoning"],
  },
];
