"""Static tool metadata for rule-based tool_search (Wave A — CH3)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

SpecialistName = Literal["retrieval_agent", "graph_agent", "writer_agent"]


@dataclass(frozen=True)
class ToolManifestEntry:
    """Human- and machine-readable tool metadata."""

    name: str
    family: str
    tags: tuple[str, ...]
    risk: Literal["low", "medium", "high"]
    scope: Literal["workspace", "graph", "corpus", "writer"]
    specialist: SpecialistName | None
    requires_workspace: bool
    prompt_summary: str
    deferred_schema_ref: str
    #: When ``agent_tool_search_strict_deferred_activation_enabled``, bind shortlist drops this
    #: tool unless it was rule-scored, merged from message history, session carry-over, or is part
    #: of the retrieval core trio baseline (workspace_inspect / paper_profile / find_works).
    strict_deferred_requires_discovery: bool = False
    #: Optional taxonomy for external HTTP tools (ADR 030); ``None`` for non-external tools.
    source_family: str | None = None


# Names must match LangChain @tool function names.
TOOL_MANIFEST: tuple[ToolManifestEntry, ...] = (
    ToolManifestEntry(
        "workspace_inspect",
        "catalog",
        ("workspace", "inventory", "count", "list", "summary", "overview"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Workspace inventory and counts",
        "tool://workspace_inspect",
        False,
    ),
    ToolManifestEntry(
        "workspace_graph_reltypes",
        "graph",
        ("workspace", "graph", "neo4j", "relationship", "rel_type", "edge", "schema"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Workspace graph relationship types/schema",
        "tool://workspace_graph_reltypes",
        True,
    ),
    ToolManifestEntry(
        "paper_profile",
        "catalog",
        ("paper", "metadata", "doi", "year", "authors", "authorship"),
        "low",
        "workspace",
        "retrieval_agent",
        False,
        "Work metadata by work_id",
        "tool://paper_profile",
    ),
    ToolManifestEntry(
        "find_works",
        "catalog",
        ("workspace", "search", "paper", "title", "entity", "fulltext", "work"),
        "low",
        "corpus",
        "retrieval_agent",
        False,
        "Find works by text/title query",
        "tool://find_works",
    ),
    ToolManifestEntry(
        "paper_quote_search",
        "evidence",
        ("quote", "chunk", "passage", "semantic", "evidence", "tradeoff", "accuracy", "speed"),
        "medium",
        "corpus",
        "retrieval_agent",
        False,
        "Semantic quote/passage retrieval",
        "tool://paper_quote_search",
        True,
    ),
    ToolManifestEntry(
        "format_bibliography_gost",
        "bibliography",
        ("bibliography", "gost", "references", "export"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Format bibliography in GOST",
        "tool://format_bibliography_gost",
        True,
    ),
    ToolManifestEntry(
        "idea_search",
        "retrieval",
        ("semantic", "chunk", "search", "idea"),
        "medium",
        "corpus",
        "retrieval_agent",
        False,
        "Semantic discovery across chunks",
        "tool://idea_search",
        True,
    ),
    ToolManifestEntry(
        "cypher_query",
        "graph",
        ("cypher", "graph", "advanced", "neo4j"),
        "high",
        "graph",
        "graph_agent",
        False,
        "Read-only Cypher graph queries",
        "tool://cypher_query",
        True,
    ),
    ToolManifestEntry(
        "edge_search",
        "graph",
        ("edge", "relation", "graph"),
        "medium",
        "graph",
        "graph_agent",
        False,
        "Edge neighborhood lookup",
        "tool://edge_search",
        True,
    ),
    ToolManifestEntry(
        "web_search",
        "external",
        ("web", "search", "doi", "literature", "arxiv", "paper", "external", "crossref"),
        "medium",
        "corpus",
        "retrieval_agent",
        False,
        "Academic web search (Crossref-backed)",
        "tool://web_search",
        True,
        source_family="crossref",
    ),
    ToolManifestEntry(
        "web_fetch",
        "external",
        ("web", "fetch", "url", "http", "https", "summary", "page"),
        "medium",
        "corpus",
        "retrieval_agent",
        False,
        "Fetch and summarize allowed scholarly URLs",
        "tool://web_fetch",
        True,
        source_family="http",
    ),
    ToolManifestEntry(
        "arxiv_search",
        "external",
        (
            "arxiv",
            "preprint",
            "paper",
            "literature",
            "abstract",
            "pdf",
            "cs.CV",
            "external",
            "search",
        ),
        "medium",
        "corpus",
        "retrieval_agent",
        False,
        "Search arXiv preprints via the official Atom API",
        "tool://arxiv_search",
        True,
        source_family="arxiv",
    ),
    ToolManifestEntry(
        "arxiv_fetch",
        "external",
        (
            "arxiv",
            "preprint",
            "paper",
            "abstract",
            "metadata",
            "pdf",
            "external",
            "fetch",
        ),
        "medium",
        "corpus",
        "retrieval_agent",
        False,
        "Fetch one arXiv record (metadata + abstract) by id or URL",
        "tool://arxiv_fetch",
        True,
        source_family="arxiv",
    ),
    ToolManifestEntry(
        "unpaywall_lookup",
        "external",
        ("doi", "open access", "oa", "unpaywall", "pdf", "url", "license", "literature"),
        "medium",
        "corpus",
        "retrieval_agent",
        False,
        "Look up OA status and best open-access URL for a DOI (Unpaywall API)",
        "tool://unpaywall_lookup",
        True,
        source_family="unpaywall",
    ),
    ToolManifestEntry(
        "doi_resolver",
        "external",
        ("doi", "openalex", "metadata", "url", "resolve", "identifier"),
        "low",
        "corpus",
        "retrieval_agent",
        False,
        "Resolve DOI or DOI URL to metadata and optional workspace work id",
        "tool://doi_resolver",
        True,
        source_family="openalex",
    ),
    ToolManifestEntry(
        "call_mcp_tool",
        "external",
        ("mcp", "server", "tool", "jsonrpc", "integration"),
        "high",
        "corpus",
        "retrieval_agent",
        False,
        "Invoke MCP tool via configured HTTP JSON-RPC adapter",
        "tool://call_mcp_tool",
        True,
    ),
    ToolManifestEntry(
        "list_mcp_resources",
        "external",
        ("mcp", "resources", "list", "server"),
        "high",
        "corpus",
        "retrieval_agent",
        False,
        "List MCP resources for a server",
        "tool://list_mcp_resources",
        True,
    ),
    ToolManifestEntry(
        "fetch_mcp_resource",
        "external",
        ("mcp", "resource", "uri", "fetch", "server"),
        "high",
        "corpus",
        "retrieval_agent",
        False,
        "Fetch MCP resource by URI",
        "tool://fetch_mcp_resource",
        True,
    ),
    ToolManifestEntry(
        "mcp_auth",
        "external",
        ("mcp", "auth", "oauth", "handoff", "server"),
        "medium",
        "corpus",
        "retrieval_agent",
        False,
        "MCP interactive auth handoff marker",
        "tool://mcp_auth",
        True,
    ),
    ToolManifestEntry(
        "lsp_tool",
        "external",
        ("lsp", "symbol", "references", "definition", "code", "ide"),
        "high",
        "corpus",
        "retrieval_agent",
        False,
        "Bounded read-only LSP workspace_symbol / references / definition",
        "tool://lsp_tool",
        True,
    ),
    ToolManifestEntry(
        "runtime_monitor_get",
        "catalog",
        ("task", "status", "progress", "heartbeat", "async", "monitor"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Read unified status snapshot for a long-running task id",
        "tool://runtime_monitor_get",
        True,
    ),
    ToolManifestEntry(
        "research_plan_write",
        "catalog",
        ("plan", "todo", "checklist", "steps", "research", "outline"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Merge structured research TODO list into session memory",
        "tool://research_plan_write",
        True,
    ),
    ToolManifestEntry(
        "ask_user_question",
        "catalog",
        ("user", "question", "choice", "clarify", "ambiguous", "options"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Structured multi-choice question to reduce ambiguity",
        "tool://ask_user_question",
        True,
    ),
    ToolManifestEntry(
        "brief",
        "catalog",
        ("summary", "brief", "card", "share", "history"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Short synthetic turn summary for history/share (<=240 chars)",
        "tool://brief",
        True,
    ),
    ToolManifestEntry(
        "enter_worktree",
        "catalog",
        ("worktree", "sandbox", "isolate", "branch", "workspace"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Enter a bounded logical worktree for isolated scratch state (session-scoped)",
        "tool://enter_worktree",
        False,
    ),
    ToolManifestEntry(
        "exit_worktree",
        "catalog",
        ("worktree", "sandbox", "isolate", "cleanup", "workspace"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Exit active worktree and release sandbox resources",
        "tool://exit_worktree",
        False,
    ),
    ToolManifestEntry(
        "enter_plan_mode",
        "catalog",
        ("plan", "readonly", "outline", "approve", "mode"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Enter read-focused plan mode (side-effect tools denied until exit_plan_mode)",
        "tool://enter_plan_mode",
        False,
    ),
    ToolManifestEntry(
        "exit_plan_mode",
        "catalog",
        ("plan", "act", "execute", "mode", "approve"),
        "low",
        "workspace",
        "retrieval_agent",
        True,
        "Exit plan mode and restore normal tool execution policy",
        "tool://exit_plan_mode",
        False,
    ),
    ToolManifestEntry(
        "final_answer",
        "writer",
        ("answer", "final"),
        "low",
        "writer",
        "writer_agent",
        False,
        "Structured final answer output",
        "tool://final_answer",
    ),
)


def manifest_by_name() -> dict[str, ToolManifestEntry]:
    """Return tool manifest entries keyed by tool name."""
    return {e.name: e for e in TOOL_MANIFEST}


def compact_catalog_lines(*, specialist: SpecialistName | None = None) -> list[str]:
    """Human-readable compact catalog lines for prompts/debug artifacts."""
    rows: list[str] = []
    for entry in TOOL_MANIFEST:
        if specialist is not None and entry.specialist not in (None, specialist):
            continue
        rows.append(f"{entry.name}: {entry.prompt_summary}")
    return rows
