#!/usr/bin/env python3
"""Aggregate Method/Dataset materialization metrics for the NLP report.

If ``--relations-suite-json`` points to a Neo4j relations benchmark suite (output of
``science-graphrag-relations-benchmark … --suite --json-out``), macro-averages the same
precision/recall/F1 fields as Layer-2 semantic scoring.

Otherwise aggregates the Layer-2 nightly suite JSON extractor output (``predicted`` field
metrics already in each case) — numerically aligned with §4.0 slot table, labeled as
**extractor JSON** rather than Neo4j read-back.

Usage::

  .venv/bin/python scripts/report_relation_graph_metrics.py
  .venv/bin/python scripts/report_relation_graph_metrics.py \\
    --relations-suite-json eval/results/relations-neo4j-pilot-suite.json
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from benchmark_aggregator.paths import DEFAULT_LAYER2_NIGHTLY, ROOT  # noqa: E402


def _mean_skip_none(values: list[float | None]) -> float | None:
    xs = [float(x) for x in values if x is not None and not math.isnan(float(x))]
    if not xs:
        return None
    return sum(xs) / len(xs)


def _f1_from_pr(p: float | None, r: float | None) -> float | None:
    if p is None or r is None:
        return None
    if p + r <= 0.0:
        return 0.0
    return (2.0 * p * r) / (p + r)


def _resolve(repo: Path, p: str) -> Path:
    path = Path(p)
    return path if path.is_absolute() else (repo / path).resolve()


def aggregate_layer2_like_cases(cases: list[dict[str, Any]]) -> dict[str, Any]:
    """Macro means over cases using metrics dict shape from layer2 or relations runners."""

    pm_list: list[float | None] = []
    rm_list: list[float | None] = []
    mf_list: list[float | None] = []
    pd_list: list[float | None] = []
    rd_list: list[float | None] = []
    df_list: list[float | None] = []
    for c in cases:
        if not isinstance(c, dict):
            continue
        m = c.get("metrics")
        if not isinstance(m, dict):
            continue
        pm = m.get("precision_methods")
        pd_ = m.get("precision_datasets")
        if m.get("recall_methods") is not None and m.get("methods_f1") is not None:
            rm = float(m["recall_methods"])
            mf = float(m["methods_f1"])
        else:
            rmn, rmd = m.get("recall_methods_num"), m.get("recall_methods_denom")
            try:
                rm = float(rmn) / float(rmd) if rmd not in (None, 0) else None
            except (TypeError, ValueError):
                rm = None
            mf = _f1_from_pr(float(pm) if pm is not None else None, rm)
        if m.get("recall_datasets") is not None and m.get("datasets_f1") is not None:
            rd = float(m["recall_datasets"])
            df = float(m["datasets_f1"])
        else:
            dsn, dsd = m.get("recall_datasets_num"), m.get("recall_datasets_denom")
            try:
                rd = float(dsn) / float(dsd) if dsd not in (None, 0) else None
            except (TypeError, ValueError):
                rd = None
            df = _f1_from_pr(float(pd_) if pd_ is not None else None, rd)
        pm_list.append(float(pm) if pm is not None else None)
        rm_list.append(rm)
        mf_list.append(mf)
        pd_list.append(float(pd_) if pd_ is not None else None)
        rd_list.append(rd)
        df_list.append(df)
    return {
        "n_cases": len(cases),
        "macro_mean": {
            "methods_precision": _mean_skip_none(pm_list),
            "methods_recall": _mean_skip_none(rm_list),
            "methods_f1": _mean_skip_none(mf_list),
            "datasets_precision": _mean_skip_none(pd_list),
            "datasets_recall": _mean_skip_none(rd_list),
            "datasets_f1": _mean_skip_none(df_list),
        },
    }


def render_markdown(payload: dict[str, Any]) -> str:
    src = payload.get("source_label", "unknown")
    mm = payload.get("macro_mean") or {}
    lines = [
        "<!-- Generated by scripts/report_relation_graph_metrics.py -->",
        "",
        "### Semantic relations (Method / Dataset)",
        "",
        f"**Source:** {src}",
        "",
        "| Slot | Macro P | Macro R | Macro F1 |",
        "|------|---------|---------|----------|",
        (
            f"| Methods | {mm.get('methods_precision')} | {mm.get('methods_recall')} | "
            f"{mm.get('methods_f1')} |"
        ),
        (
            f"| Datasets | {mm.get('datasets_precision')} | {mm.get('datasets_recall')} | "
            f"{mm.get('datasets_f1')} |"
        ),
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=ROOT)
    parser.add_argument(
        "--relations-suite-json",
        type=str,
        default="",
        help="Optional Neo4j relations suite JSON.",
    )
    parser.add_argument(
        "--layer2-fallback-json",
        type=str,
        default=DEFAULT_LAYER2_NIGHTLY,
        help="Layer-2 suite JSON used when relations suite is missing.",
    )
    parser.add_argument(
        "--out-json",
        type=str,
        default="eval/results/relations-graph-for-report.json",
    )
    parser.add_argument(
        "--out-md",
        type=str,
        default="eval/results/relations-graph-for-report.md",
    )
    args = parser.parse_args(argv)
    repo = args.repo_root.resolve()
    rel_path = (args.relations_suite_json or "").strip()
    if rel_path:
        p = _resolve(repo, rel_path)
        if not p.is_file():
            print(f"Missing relations suite: {p}", file=sys.stderr)
            return 1
        raw = json.loads(p.read_text(encoding="utf-8"))
        cases = raw.get("cases") or []
        agg = aggregate_layer2_like_cases(cases if isinstance(cases, list) else [])
        payload: dict[str, Any] = {
            "inputs": {"relations_suite_json": str(p)},
            "run_metadata": raw.get("run_metadata") or {},
            "source_label": "neo4j_relations_benchmark_suite",
            "aggregation": "macro_mean_over_cases",
            **agg,
        }
    else:
        p = _resolve(repo, args.layer2_fallback_json)
        if not p.is_file():
            print(f"Missing layer2 fallback: {p}", file=sys.stderr)
            return 1
        raw = json.loads(p.read_text(encoding="utf-8"))
        cases = raw.get("cases") or []
        agg = aggregate_layer2_like_cases(cases if isinstance(cases, list) else [])
        payload = {
            "inputs": {"layer2_suite_json": str(p)},
            "run_metadata": raw.get("run_metadata") or {},
            "source_label": (
                "layer2_suite_extractor_json_metrics "
                "(aligned with §4.0; run `science-graphrag-relations-benchmark` "
                "for Neo4j read-back on tier `relations_pilot`)"
            ),
            "aggregation": "macro_mean_over_cases",
            **agg,
        }
    out_json = _resolve(repo, args.out_json)
    out_md = _resolve(repo, args.out_md)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    out_md.write_text(render_markdown(payload), encoding="utf-8")
    print(f"Wrote {out_json}")
    print(f"Wrote {out_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
