#!/usr/bin/env python3
"""Aggregate Neo4j CITES (cited arXiv) metrics from a graph-level benchmark suite JSON.

Reads a suite artifact produced by ``science-graphrag-graph-benchmark … --suite --json-out``
(default: ``eval/results/graph-suite-api-latest.json``) and writes report-facing macro means
over cases with ``metrics.has_expectations`` true.

Usage (repo root)::

  .venv/bin/python scripts/report_graph_cites_metrics.py
  .venv/bin/python scripts/report_graph_cites_metrics.py \\
    --graph-suite-json eval/results/my-graph-suite.json \\
    --out-json eval/results/graph-cites-for-report.json
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from benchmark_aggregator.paths import ROOT  # noqa: E402


def _mean_skip_none(values: list[float | None]) -> float | None:
    xs = [float(x) for x in values if x is not None and not math.isnan(float(x))]
    if not xs:
        return None
    return sum(xs) / len(xs)


def _resolve(repo: Path, p: str) -> Path:
    path = Path(p)
    return path if path.is_absolute() else (repo / path).resolve()


def aggregate_graph_cites(suite: dict[str, Any]) -> dict[str, Any]:
    cases = suite.get("cases") or []
    precisions: list[float | None] = []
    recalls: list[float | None] = []
    f1s: list[float | None] = []
    case_rows: list[dict[str, Any]] = []
    for c in cases:
        if not isinstance(c, dict):
            continue
        cid = c.get("case_id")
        m = c.get("metrics") if isinstance(c, dict) else None
        if not isinstance(m, dict) or not m.get("has_expectations"):
            continue
        p = m.get("cited_arxiv_precision")
        r = m.get("cited_arxiv_recall")
        f = m.get("cited_arxiv_f1")
        try:
            precisions.append(float(p) if p is not None else None)
        except (TypeError, ValueError):
            precisions.append(None)
        try:
            recalls.append(float(r) if r is not None else None)
        except (TypeError, ValueError):
            recalls.append(None)
        try:
            f1s.append(float(f) if f is not None else None)
        except (TypeError, ValueError):
            f1s.append(None)
        passed = None
        contract = m.get("contract")
        if isinstance(contract, dict):
            passed = bool(contract.get("passed"))
        case_rows.append(
            {
                "case_id": cid,
                "cited_arxiv_precision": precisions[-1],
                "cited_arxiv_recall": recalls[-1],
                "cited_arxiv_f1": f1s[-1],
                "contract_passed": passed,
            },
        )
    return {
        "n_cases_in_suite": len(cases) if isinstance(cases, list) else 0,
        "n_cases_with_graph_expectations": len(precisions),
        "macro_mean": {
            "cited_arxiv_precision": _mean_skip_none(precisions),
            "cited_arxiv_recall": _mean_skip_none(recalls),
            "cited_arxiv_f1": _mean_skip_none(f1s),
        },
        "per_case": case_rows,
    }


def render_markdown(payload: dict[str, Any]) -> str:
    mm = payload.get("macro_mean") or {}
    n_exp = payload.get("n_cases_with_graph_expectations")
    n_all = payload.get("n_cases_in_suite")
    lines = [
        "<!-- Generated by scripts/report_graph_cites_metrics.py -->",
        "",
        "### Graph materialization: CITES (arXiv ids in Neo4j vs gold)",
        "",
        f"Cases with `graph_expectations` in suite: **{n_exp}** / **{n_all}** in input artifact.",
        "",
        "| Metric | Macro mean |",
        "|--------|------------|",
        f"| cited_arxiv precision | {mm.get('cited_arxiv_precision')} |",
        f"| cited_arxiv recall | {mm.get('cited_arxiv_recall')} |",
        f"| cited_arxiv F1 | {mm.get('cited_arxiv_f1')} |",
        "",
        "Source: `science-graphrag-graph-benchmark` suite JSON (`cited_arxiv_*` fields).",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=ROOT,
        help="Repository root.",
    )
    parser.add_argument(
        "--graph-suite-json",
        type=str,
        default="eval/results/graph-suite-api-latest.json",
        help="Graph benchmark suite JSON (suite shape with cases[].metrics).",
    )
    parser.add_argument(
        "--out-json",
        type=str,
        default="eval/results/graph-cites-for-report.json",
    )
    parser.add_argument(
        "--out-md",
        type=str,
        default="eval/results/graph-cites-for-report.md",
    )
    args = parser.parse_args(argv)
    repo = args.repo_root.resolve()
    path = _resolve(repo, args.graph_suite_json)
    if not path.is_file():
        print(f"Missing graph suite file: {path}", file=sys.stderr)
        return 1
    suite = json.loads(path.read_text(encoding="utf-8"))
    agg = aggregate_graph_cites(suite)
    payload: dict[str, Any] = {
        "inputs": {"graph_suite_json": str(path)},
        "run_metadata": suite.get("run_metadata") or {},
        "aggregation": "macro_mean_over_cases_with_has_expectations_true",
        **agg,
    }
    out_json = _resolve(repo, args.out_json)
    out_md = _resolve(repo, args.out_md)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    out_md.write_text(render_markdown(payload), encoding="utf-8")
    print(f"Wrote {out_json}")
    print(f"Wrote {out_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
